### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by sonia3994** [rat-pac/rat-pac#46]
below 91 GeV, Glauber-Gribov above 
     Cr_sctns:          GheishaInelastic: 0 eV  ---> 100 TeV

  Process: hBertiniCaptureAtRest

---------------------------------------------------
                           Hadronic Processes for proton

  Process: hadElastic
        Model:             hElasticCHIPS: 0 eV  ---> 100 TeV
     Cr_sctns:      ChipsProtonElasticXS: 0 eV  ---> 100 TeV
     Cr_sctns:            GheishaElastic: 0 eV  ---> 100 TeV

  Process: protonInelastic
        Model:                      FTFP: 4 GeV ---> 100 TeV
        Model:            BertiniCascade: 0 eV  ---> 5 GeV
     Cr_sctns:       Barashenkov-Glauber: 0 eV  ---> 100 TeV
     Cr_sctns:          GheishaInelastic: 0 eV  ---> 100 TeV

================================================================
Gsim: Simulating run 1
Gsim: Run start at Mon, 02 Nov 2015 08:44:24 +0000 (GMT) +875897000 nsec
Setting up PDF PMTTime model for DEFAULT
rat: symbol lookup error: rat: undefined symbol: _ZN8TVector3C1Ev
geant4@ubuntu:~/Desktop/rat-pac$

**Comment by nbarros** [comment]
@sonia3994 It seems that it is not finding the library with ```TVector3``` definition. Can you tell me which version of ROOT are you using and if you have the location of the respective libraries in your ```LD_LIBRARY_PATH```?

```TVector3``` is usually (at least in versions < 5.x) in ```libPhysics.so```.
Could you check that all the necessary environment is set up?

**Comment by sonia3994** [comment]
geant4@ubuntu:~$ root
  *******************************************
  *                                         *
  *        W E L C O M E  to  R O O T       *
  *                                         *
  *   Version   5.34/18     14 March 2014   *
  *                                         *
  *  You are welcome to visit our Web site  *
  *          http://root.cern.ch            *
  *                                         *
  *******************************************

**Comment by nbarros** [comment]
Ok, thanks. can you also post the outputs of the following commands?

```echo $LD_LIBRARY_PATH```
```which root```
```ls $ROOTSYS/lib```
```ls $ROOTSYS/lib/root```

Finally, you don't have more than one ROOT installation in your system, do you?

**Comment by sonia3994** [comment]
geant4@ubuntu:~$ echo $LD_LIBRARY_PATH
/usr/lib/x86_64-linux-gnu:/projects/soft/ext/geant4.10.00.p02-install/lib:/projects/soft/ext/root/pro/lib

geant4@ubuntu:~$ which root
/projects/soft/ext/root/pro/bin/root

geant4@ubuntu:~$ ls $ROOTSYS/lib
cppyy.py                libHbook.so               libRGL.rootmap
cppyy.pyc               libHistFactory.rootmap    libRGL.so
cppyy.pyo               libHistFactory.so         libRint.rootmap
libAfterImage.a         libHistPainter.rootmap    libRint.so
libASImageGui.rootmap   libHistPainter.so         libRIO.rootmap
libASImageGui.so        libHist.rootmap           libRIO.so
libASImage.rootmap      libHist.so                libRLDAP.rootmap
libASImage.so           libHtml.rootmap           libRLDAP.so
libCintex.rootmap       libHtml.so                libRMySQL.rootmap
libCintex.so            libKrb5Auth.rootmap       libRMySQL.so
libCint.so              libKrb5Auth.so            libRooFitCore.rootmap
libcomplexDict.rootmap  liblistDict.rootmap       libRooFitCore.so
libcomplexDict.so       liblistDict.so            libRooFit.rootmap
libCore.rootmap         liblzma.a                 libRooFit.so
libCore.so              libmap2Dict.rootmap       libRooStats.rootmap
libdequeDict.rootmap    libmap2Dict.so            libRooStats.so
libdequeDict.so         libmapDict.rootmap        libRootAuth.rootmap
libEG.rootmap           libmapDict.so             libRootAuth.so
libEG.so                libMathCore.rootmap       libSessionViewer.rootmap
libEve.rootmap          libMathCore.so            libSessionViewer.so
libEve.so               libMathMore.rootmap       libsetDict.rootmap
libFFTW.rootmap         libMathMore.so            libsetDict.so
libFFTW.so              libmathtext.a             libSmatrix.rootmap
libFitPanel.rootmap     libMatrix.rootmap         libSmatrix.so
libFitPanel.so          libMatrix.so              libSpectrumPainter.rootmap
libFITSIO.rootmap       libMemStat.rootmap        libSpectrumPainter.so
libFITSIO.so            libMemStat.so             libSpectrum.rootmap
libFoam.rootmap         libminicern.so            libSpectrum.so
libFoam.so              libMinuit2.rootmap        libSPlot.rootmap
libfreetype.a           libMinuit2.so             libSPlot.so
libFumili.rootmap       libMinuit.rootmap         libSQLIO.rootmap
libFumili.so            libMinuit.so              libSQLIO.so
libGdml.rootmap         libMLP.rootmap            libSrvAuth.so
libGdml.so              libMLP.so                 libTable.rootmap
libGed.rootmap          libmultimap2Dict.rootmap  libTable.so
libGed.so               libmultimap2Dict.so       libThread.rootmap
libGenetic.rootmap      libmultimapDict.rootmap   libThread.so
libGenetic.so           libmultimapDict.so        libTMVA.rootmap
libGenVector.rootmap    libmultisetDict.rootmap   libTMVA.so
libGenVector.so         libmultisetDict.so        libTreePlayer.rootmap
libGeomBuilder.rootmap  libNet.rootmap            libTreePlayer.so
libGeomBuilder.so       libNet.so                 libTree.rootmap
libGeomPainter.rootmap  libNew.so                 libTree.so
libGeomPainter.so       libpcre.a                 libTreeViewer.rootmap
libGeom.rootmap         libPhysics.rootmap        libTreeViewer.so
libGeom.so              libPhysics.so             libUnuran.rootmap
libGpad.rootmap         libPostscript.rootmap     libUnuran.so
libGpad.so              libPostscript.so          libvalarrayDict.rootmap
libGQt.rootmap          libProofBench.rootmap     libvalarrayDict.so
libGQt.so               libProofBench.so          libvectorDict.rootmap
libGraf3d.rootmap       libProofDraw.rootmap      libvectorDict.so
libGraf3d.so            libProofDraw.so           libVMC.rootmap
libGraf.rootmap         libProofPlayer.rootmap    libVMC.so
libGraf.so              libProofPlayer.so         libX3d.rootmap
libGuiBld.rootmap       libProof.rootmap          libX3d.so
libGuiBld.so            libProof.so               libXMLIO.rootmap
libGuiHtml.rootmap      libPyROOT.rootmap         libXMLIO.so
libGuiHtml.so           libPyROOT.so              libXMLParser.rootmap
libGui.rootmap          libQtGSI.rootmap          libXMLParser.so
libGui.so               libQtGSI.so               PyCintex.py
libGviz3d.rootmap       libQtRoot.rootmap         PyCintex.pyc
libGviz3d.so            libQtRoot.so              PyCintex.pyo
libGviz.rootmap         libQuadp.rootmap          python
libGviz.so              libQuadp.so               ROOT.py
libGX11.rootmap         libRecorder.rootmap       ROOT.pyc
libGX11.so              libRecorder.so            ROOT.pyo
libGX11TTF.rootmap      libReflexDict.rootmap     ROOTwriter.py
libGX11TTF.so           libReflexDict.so          writer.py
libHbook.rootmap        libReflex.so

geant4@ubuntu:~$ ls $ROOTSYS/lib/root
ls: cannot access /projects/soft/ext/root/pro/lib/root: No such file or directory

**Comment by sonia3994** [comment]
Thanks for your help! :)

**Comment by sdrountree** [comment]
I managed to reproduce the error.
you need geant4.10.01.p02

On 11/2/2015 10:07 AM, Ghulam Hussain wrote:
>
> geant4@ubuntu:~$ echo $LD_LIBRARY_PATH
> /usr/lib/x86_64-linux-gnu:/projects/soft/ext/geant4.10.00.p02-install/lib:/projects/soft/ext/root/pro/lib
>
> geant4@ubuntu:~$ which root
> /projects/soft/ext/root/pro/bin/root
>
> geant4@ubuntu:~$ ls $ROOTSYS/lib
> cppyy.py libHbook.so libRGL.rootmap
> cppyy.pyc libHistFactory.rootmap libRGL.so
> cppyy.pyo libHistFactory.so libRint.rootmap
> libAfterImage.a libHistPainter.rootmap libRint.so
> libASImageGui.rootmap libHistPainter.so libRIO.rootmap
> libASImageGui.so libHist.rootmap libRIO.so
> libASImage.rootmap libHist.so libRLDAP.rootmap
> libASImage.so libHtml.rootmap libRLDAP.so
> libCintex.rootmap libHtml.so libRMySQL.rootmap
> libCintex.so libKrb5Auth.rootmap libRMySQL.so
> libCint.so libKrb5Auth.so libRooFitCore.rootmap
> libcomplexDict.rootmap liblistDict.rootmap libRooFitCore.so
> libcomplexDict.so liblistDict.so libRooFit.rootmap
> libCore.rootmap liblzma.a libRooFit.so
> libCore.so libmap2Dict.rootmap libRooStats.rootmap
> libdequeDict.rootmap libmap2Dict.so libRooStats.so
> libdequeDict.so libmapDict.rootmap libRootAuth.rootmap
> libEG.rootmap libmapDict.so libRootAuth.so
> libEG.so libMathCore.rootmap libSessionViewer.rootmap
> libEve.rootmap libMathCore.so libSessionViewer.so
> libEve.so libMathMore.rootmap libsetDict.rootmap
> libFFTW.rootmap libMathMore.so libsetDict.so
> libFFTW.so libmathtext.a libSmatrix.rootmap
> libFitPanel.rootmap libMatrix.rootmap libSmatrix.so
> libFitPanel.so libMatrix.so libSpectrumPainter.rootmap
> libFITSIO.rootmap libMemStat.rootmap libSpectrumPainter.so
> libFITSIO.so libMemStat.so libSpectrum.rootmap
> libFoam.rootmap libminicern.so libSpectrum.so
> libFoam.so libMinuit2.rootmap libSPlot.rootmap
> libfreetype.a libMinuit2.so libSPlot.so
> libFumili.rootmap libMinuit.rootmap libSQLIO.rootmap
> libFumili.so libMinuit.so libSQLIO.so
> libGdml.rootmap libMLP.rootmap libSrvAuth.so
> libGdml.so libMLP.so libTable.rootmap
> libGed.rootmap libmultimap2Dict.rootmap libTable.so
> libGed.so libmultimap2Dict.so libThread.rootmap
> libGenetic.rootmap libmultimapDict.rootmap libThread.so
> libGenetic.so libmultimapDict.so libTMVA.rootmap
> libGenVector.rootmap libmultisetDict.rootmap libTMVA.so
> libGenVector.so libmultisetDict.so libTreePlayer.rootmap
> libGeomBuilder.rootmap libNet.rootmap libTreePlayer.so
> libGeomBuilder.so libNet.so libTree.rootmap
> libGeomPainter.rootmap libNew.so libTree.so
> libGeomPainter.so libpcre.a libTreeViewer.rootmap
> libGeom.rootmap libPhysics.rootmap libTreeViewer.so
> libGeom.so libPhysics.so libUnuran.rootmap
> libGpad.rootmap libPostscript.rootmap libUnuran.so
> libGpad.so libPostscript.so libvalarrayDict.rootmap
> libGQt.rootmap libProofBench.rootmap libvalarrayDict.so
> libGQt.so libProofBench.so libvectorDict.rootmap
> libGraf3d.rootmap libProofDraw.rootmap libvectorDict.so
> libGraf3d.so libProofDraw.so libVMC.rootmap
> libGraf.rootmap libProofPlayer.rootmap libVMC.so
> libGraf.so libProofPlayer.so libX3d.rootmap
> libGuiBld.rootmap libProof.rootmap libX3d.so
> libGuiBld.so libProof.so libXMLIO.rootmap
> libGuiHtml.rootmap libPyROOT.rootmap libXMLIO.so
> libGuiHtml.so libPyROOT.so libXMLParser.rootmap
> libGui.rootmap libQtGSI.rootmap libXMLParser.so
> libGui.so libQtGSI.so PyCintex.py
> libGviz3d.rootmap libQtRoot.rootmap PyCintex.pyc
> libGviz3d.so libQtRoot.so PyCintex.pyo
> libGviz.rootmap libQuadp.rootmap python
> libGviz.so libQuadp.so ROOT.py
> libGX11.rootmap libRecorder.rootmap ROOT.pyc
> libGX11.so libRecorder.so ROOT.pyo
> libGX11TTF.rootmap libReflexDict.rootmap ROOTwriter.py
> libGX11TTF.so libReflexDict.so writer.py
> libHbook.rootmap libReflex.so
>
> geant4@ubuntu:~$ ls $ROOTSYS/lib/root
> ls: cannot access /projects/soft/ext/root/pro/lib/root: No such file or directory
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/rat-pac/rat-pac/issues/46#issuecomment-153045570>.
>

-- 
S. Derek Rountree
miniLENS Project Manager
KURF Laboratory Manager
Virginia Tech
Department of Physics (MC 0435)
850 West Campus Drive, Blacksburg, VA 24061


Cell Ph#: (540) 250-1648
KURF Ph#: (540) 626-5559
Fax#    : (540) 231-7511

**Comment by sonia3994** [comment]
I am very greatful to you and your help. I will update my geant4 version and then let you know the status. 
Thanks. 
Have a good day:)

**Comment by sdrountree** [comment]
Thanks,
installation instructions can be found at: http://rat.readthedocs.org/en/latest/installation.html
On 11/2/2015 10:20 AM, Ghulam Hussain wrote:
>
> I am very greatful to you and your help. I will update my geant4 version and then let you know the status.
> Thanks.
> Have a good day:)
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/rat-pac/rat-pac/issues/46#issuecomment-153050765>.
>

-- 
S. Derek Rountree
miniLENS Project Manager
KURF Laboratory Manager
Virginia Tech
Department of Physics (MC 0435)
850 West Campus Drive, Blacksburg, VA 24061


Cell Ph#: (540) 250-1648
KURF Ph#: (540) 626-5559
Fax#    : (540) 231-7511

**Comment by nbarros** [comment]
That error is usually a sign of one of the following:
* Different parts of the code were compiled with different library versions
* Mismatch between the version of the library available at runtime and the library used at compilation time

Could you please try to make a clean build of RAT?

**Comment by sonia3994** [comment]
Dear nbarros,

I will pay attention to all parts of the code with different ver. 
I am going to compile a fresh copy of RAT. Thanks to you and Derek.

**Comment by sonia3994** [comment]
Thanks for your help :) Derek  and nbarros
