### ISSUE TITLE
DB parser accepts invalid input in OPTICS.ratdb

### ISSUE THREAD

**Issue by sglavin** [rat-pac/rat-pac#47]
It appears that while changing from MiniCLEAN RAT’s use of d’s for doubles to RAT-PAC’s use of e’s, there were a few typos. It should be changed to fail for invalid inputs. It should throw an exception, but it does not (and seems to be reading some value).

OPTICS.ratdb examples
for both acrylic_uvt_RPT (line 708) and acrylic_uva_McMaster (line 746):
“ABSLENGTH_value2: [1.0-3,1.0-3,”

**Comment by mastbaum** [comment]
Can you take a look at this @BenLand100?

**Comment by mastbaum** [comment]
Closed by #37, which included changes from #49.
