### ISSUE TITLE
The RAT-PAC Cf source produces neutrons with unphysically low kinetic energies

### ISSUE THREAD

**Issue by sjgardiner** [rat-pac/rat-pac#55]
Although the californium generator appears to sample the neutron kinetic energies correctly, the corresponding particles in the RAT-PAC simulation do not have the right energy distribution. Here's an example using 1e4 events.
![buggy_nkes_plot](https://cloud.githubusercontent.com/assets/7638176/24994129/4c35aeca-1fde-11e7-9af7-0e5fed2be389.png)

**Comment by sjgardiner** [comment]
Pull request #54 resolves this issue. Please merge! :smiley:

**Comment by mastbaum** [comment]
Closed by #54.
